tello_navigator:
  ros__parameters:
    ns_abs: "/drone1"

    map_frame: "map"
    base_link_frame: "base_link_1"

    takeoff_height_m: 0.5

    auto_takeoff: true
    auto_start: true
    require_start_service: true
    speed_cmps: 20
    debug: true

    hold_after_takeoff_s: 5.0
    hold_between_waypoints_s: 0.0

    probe_child_frame: "camera_link_1"
    wait_for_base_link_timeout_s: 15.0

    # Cada item: "[dx, dy, dz, speed, delay_s]"
    waypoints_list:
      - "[500, 100, 500, 100, 3.0]" # tf de teste para o base_localization
      - "[0, 400, 0, 100, 3.0]" # para a esquerda
      - "[-400, 0, 0, 100, 3.0]" # para a tras
      - "[0, -300, 0, 100, 3.0]" # para a tras

      # - "[85, 60, 260, 20, 3.0]" # primeira tf (1x,1y)
      # - "[160, 0, 0, 20, 4.0]" # casa 2x1y
      # - "[160, 0, 0, 20, 4.0]" # casa 3x1y
      # - "[160, 0, 0, 20, 4.0]" # casa 4x1y
      # - "[0, 160, 0, 20, 4.0]" # casa 4x2y
      # - "[-160, 0, 0, 20, 4.0]" # casa 3x2y
      # - "[-160, 0, 0, 20, 4.0]" # casa 2x2y
      # - "[-160, 0, 0, 20, 4.0]" # casa 1x2y
      # - "[0, 160, 0, 20, 4.0]" # casa 1x3y
      # - "[160, 0, 0, 20, 4.0]" # casa 2x3y
      # - "[160, 0, 0, 20, 4.0]" # casa 3x3y
      # - "[160, 0, 0, 20, 4.0]" # casa 4x3y
      # - "[0, 160, 0, 20, 4.0]" # casa 4x4y
      # - "[-160, 0, 0, 20, 4.0]" # casa 3x4y
      # - "[-160, 0, 0, 20, 4.0]" # casa 2x4y
      # - "[-160, 0, 0, 20, 4.0]" # casa 1x4y
