base_localization:
  ros__parameters:
    # Tópico com bboxes [x1,y1,x2,y2,score,...]
    detected_coords_topic: "/base_detection/detected_coords"

    # Frames (AJUSTADOS)
    camera_frame: "espcam_link_1"   # << existe no seu /tf_static
    drone_frame:  "base_link_1"     # << existe no seu /tf

    # Alvo
    square_size_m: 1.0
    min_score: 0.25

    # Câmera (pinhole) — intrínsecos e distorção
    camera:
      # K = [fx, 0, cx,  0, fy, cy,  0, 0, 1]  (AJUSTE para sua calibração real)
      K: [600.0, 0.0, 320.0,  0.0, 600.0, 240.0,  0.0, 0.0, 1.0]
      # D = [k1, k2, p1, p2, k3] (plumb_bob/OpenCV). Ajuste conforme sua calibração.
      D: [0.0, 0.0, 0.0, 0.0, 0.0]
